/*
 * generated by Xtext
 */
package com.ihaomo.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SqlsUiModule extends com.ihaomo.language.ui.AbstractSqlsUiModule {
	public SqlsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
