/*
* generated by Xtext
*/
package com.ihaomo.language;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SqlsStandaloneSetup extends SqlsStandaloneSetupGenerated{

	public static void doSetup() {
		new SqlsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

