/*
 * generated by Xtext
 */
package com.ihaomo.language.ui.contentassist

import com.ihaomo.language.ui.contentassist.AbstractSqlsProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SqlsProposalProvider extends AbstractSqlsProposalProvider {
}
